// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYIXy4jIwQa86F3TMllTlNgpr6t7MZoQ',
    appId: '1:799203422311:web:7358685b111c3df95a64c2',
    messagingSenderId: '799203422311',
    projectId: 'kayla-eddd7',
    authDomain: 'kayla-eddd7.firebaseapp.com',
    storageBucket: 'kayla-eddd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOEYJ0gMqDguypLHFl8JplVDXs_U_xNg',
    appId: '1:799203422311:android:91cc9b29232709955a64c2',
    messagingSenderId: '799203422311',
    projectId: 'kayla-eddd7',
    storageBucket: 'kayla-eddd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zBQ3BA0uhu9Wp6J3K09MT8gn7a6uaIU',
    appId: '1:799203422311:ios:9c81061cbfef24a85a64c2',
    messagingSenderId: '799203422311',
    projectId: 'kayla-eddd7',
    storageBucket: 'kayla-eddd7.appspot.com',
    iosBundleId: 'com.example.doctorBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zBQ3BA0uhu9Wp6J3K09MT8gn7a6uaIU',
    appId: '1:799203422311:ios:9c81061cbfef24a85a64c2',
    messagingSenderId: '799203422311',
    projectId: 'kayla-eddd7',
    storageBucket: 'kayla-eddd7.appspot.com',
    iosBundleId: 'com.example.doctorBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhYIXy4jIwQa86F3TMllTlNgpr6t7MZoQ',
    appId: '1:799203422311:web:3fdc8102ef6717465a64c2',
    messagingSenderId: '799203422311',
    projectId: 'kayla-eddd7',
    authDomain: 'kayla-eddd7.firebaseapp.com',
    storageBucket: 'kayla-eddd7.appspot.com',
  );
}
